spring:
  profiles:
    active: dev
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update

---
spring:
  profiles: dev
  datasource:
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/taotao?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 5
      pool-name: DatebookHikariCP
#  redis:
#    host: 127.0.0.1
##    password: redispassword
#    port: 6379
##    cluster:
##      nodes: 192.168.211.134:7000,192.168.211.134:7001,192.168.211.134:7002
##      maxRedirects: 6
#    jedis:
#      pool:
#        max-idle: 8
#        max-wait: -1
#        min-idle: 0
#        max-active: 8
#    timeout: 5000







